# This is a basic workflow to help you get started with Actions

name: CICD_BUILD_WORKFLOW

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    # Runs a single command using the runners shellf
    strategy:
      fail-fast: false
      matrix:
        build_type: [ 'jvm' ] # ['jvm', 'native']
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          settings-path: ${{ github.workspace }}
      - name: build
        run: |
          mvn -v
          mvn -X -B install --file pom.xml -DskipTests
      - name: Publish to GitHub Packages Apache Maven
        run:  |
          mvn -X -B deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    # Runs a single command using the runners shel
    needs: build
    strategy:
      fail-fast: false
      matrix:
        build_type: [ 'jvm' ] # ['jvm', 'native']
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Maven setup
        uses: stCarolas/setup-maven@v4.2
      - name: test
        run: |
          java --version
          mvn -X -B test --file pom.xml

  report:
    # Runs a single command using the runners shell
    needs: test
    strategy:
      fail-fast: false
      matrix:
        build_type: [ 'jvm' ] # ['jvm', 'native']
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      -  uses: stCarolas/setup-maven@v4.2
      -  run: |
          java --version
          mvn -X -B verify --file pom.xml
      uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov

  quality:
    # Runs a single command using the runners shell
    needs: report
    strategy:
      fail-fast: false
      matrix:
        build_type: [ 'jvm' ] # ['jvm', 'native']
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Maven setup
        uses: stCarolas/setup-maven@v4.2
      - name: quality
        run: |
          java --version
          echo "RUNNING QUALITY GATES STEP"

  docker:
    # Runs a single command using the runners shell
    runs-on: [ ubuntu-latest ]
    needs: quality
    steps:
      - name: Run Docker
        run: echo "RUNNING BUILD DOCKER IMAGE STEP"
