# This is a basic workflow to help you get started with Actions

name: CICD_BUILD_WORKFLOW

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    # Runs a single command using the runners shellf
    strategy:
      fail-fast: false
      matrix:
        build_type: [ 'jvm' ] # ['jvm', 'native']
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [
                    {
                        "id": "github",
                        "interactiveMode": "false",
                        "username": "$GITHUB_ACTOR",
                        "password": "$GITHUB_TOKEN",
                        "activeProfiles": "github",
                        "profiles": {
                            "profile": 
                            {
                                "id": "github",
                                "repositories": {
                                    "repository":  {
                                        "id": "github",
                                        "snapshots": "true",
                                        "url": "https://repo1.maven.org/maven2"
                                    },
                                    "repository":  {
                                        "id": "github",
                                        "snapshots": "true",
                                        "url": "https://maven.pkg.github.com/hundzukani/cicd"
                                    }
                                }
                            }
                        },
                        "servers": {
                            "id": "github",
                            "username": "$GITHUB_ACTOR",
                            "password": "$GITHUB_TOKEN"
                        }
                    }
                ]
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Maven setup
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.3
      - name: build
        run: |
          mvn -v
          mvn -X -B install --file pom.xml -DskipTests
          cat settings.xml
          mvn -X deploy
          cd /home/runner/.m2/repository
          ls

  test:
    # Runs a single command using the runners shel
    needs: build
    strategy:
      fail-fast: false
      matrix:
        build_type: [ 'jvm' ] # ['jvm', 'native']
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Maven setup
        uses: stCarolas/setup-maven@v4.2
      - name: test
        run: |
          java --version
          mvn -X -B test --file pom.xml

  report:
    # Runs a single command using the runners shell
    needs: test
    strategy:
      fail-fast: false
      matrix:
        build_type: [ 'jvm' ] # ['jvm', 'native']
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Maven setup
        uses: stCarolas/setup-maven@v4.2
      - name: report
        run: |
          java --version
          mvn -X -B verify --file pom.xml

  quality:
    # Runs a single command using the runners shell
    needs: report
    strategy:
      fail-fast: false
      matrix:
        build_type: [ 'jvm' ] # ['jvm', 'native']
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Maven setup
        uses: stCarolas/setup-maven@v4.2
      - name: quality
        run: |
          java --version
          echo "RUNNING QUALITY GATES STEP"

  docker:
    # Runs a single command using the runners shell
    runs-on: [ ubuntu-latest ]
    needs: quality
    steps:
      - name: Run Docker
        run: echo "RUNNING BUILD DOCKER IMAGE STEP"
