# This is a basic workflow to help you get started with Actions

name: SELF_HOSTED_WORKFLOW

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: [ self-hosted ]
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          settings-path: ${{ github.workspace }}
      - name: build
        run: |
          mvn -v
          mvn -X -B install --file pom.xml -DskipTests
